/**
 * Regenerates src/upstream-gaps/index.ts WHOLESALE from the directory listing: the derivations split the two gap
 * kinds by their `kind` field, so nothing but the file names is needed.
 *   a gap file added by hand                     -> `bun .github/scripts/gen-gaps-index.ts`
 *   graduate-upstream-gaps.ts                    -> calls regenerateIndex() itself
 *   test/scripts/graduate-upstream-gaps.test.ts  -> pins the committed index to a fresh regeneration
 */

import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { countNoun } from "../../src/text.js";

const ROOT = join(import.meta.dir, "..", "..");
const GAPS_DIR = "src/upstream-gaps";
export const INDEX_PATH = `${GAPS_DIR}/index.ts`;

export const NON_GAP_FILE_NAMES: ReadonlySet<string> = new Set(["index.ts", "gap.ts"]);

/** A stray notes.d.ts or a test must not regenerate into a phantom import. */
export function isGapFileName(name: string): boolean {
  return (
    name.endsWith(".ts") &&
    !name.endsWith(".d.ts") &&
    !name.endsWith(".test.ts") &&
    !NON_GAP_FILE_NAMES.has(name)
  );
}

/** "merge-queue" -> "mergeQueue": the generated import alias for a gap file. */
export function camelCaseGapName(base: string): string {
  return base.replace(/-([a-z0-9])/g, (_, ch: string) => ch.toUpperCase());
}

export function gapFileBases(listing: readonly string[]): string[] {
  return listing
    .filter(isGapFileName)
    .map((name) => name.replace(/\.ts$/, ""))
    .sort();
}

/** Pure and deterministic (the bases are re-sorted), so tests compare the committed index against a fresh render
 * without touching the disk. */
export function generateIndex(bases: readonly string[]): string {
  const sorted = [...bases].sort();
  const imports = [
    { specifier: "./gap.js", line: `import { undocumentedRoutes } from "./gap.js";` },
    ...sorted.map((base) => ({
      specifier: `./${base}.js`,
      line: `import { GAP as ${camelCaseGapName(base)} } from "./${base}.js";`,
    })),
  ]
    .sort((a, b) => (a.specifier < b.specifier ? -1 : 1))
    .map((entry) => entry.line)
    .join("\n");
  const gapsArray =
    sorted.length === 0
      ? "const GAPS = [] as const;"
      : [
          "const GAPS = [",
          ...sorted.map((base) => `  ${camelCaseGapName(base)},`),
          "] as const;",
        ].join("\n");
  return `/**
 * GENERATED by gen-gaps-index.ts - do not edit. Every pending upstream gap,
 * aggregated in sorted file order; regenerate with
 * \`bun .github/scripts/gen-gaps-index.ts\` after adding, deleting, or
 * transforming a gap file. The derivations below degrade gracefully to an
 * empty gaps set, so this file survives an empty directory.
 */

${imports}

${gapsArray}

type GapUnion = (typeof GAPS)[number];

/**
 * Routes GitHub documents but the pinned @octokit/types release does not
 * carry yet: the octokit-kind gaps' routes (spec-only gaps are keyof
 * Endpoints already). Only the route STRING is consumed (never octokit's
 * parameter/response typing), so the literal union defineGap preserves is
 * enough; an empty GAPS degrades it to never.
 */
export type SupplementalRoute = Extract<GapUnion, { kind: "octokit" }>["routes"][number];

/** The spec-only gaps' routes: typed by octokit, absent from the descriptor. */
type SpecOnlyRoute = Extract<GapUnion, { kind: "spec-only" }>["routes"][number];

/**
 * The routes GitHub's api.github.com OpenAPI descriptor does not document:
 * every spec-only gap's, plus those of octokit-kind gaps marked
 * documentedInSpec: false. Consumed by test/e2e/openapi/paths.ts, which
 * excludes their paths from the spec trim and exempts exactly these
 * METHOD+path pairs from the e2e unknown-route check.
 */
export const UNDOCUMENTED_ROUTES: readonly (SupplementalRoute | SpecOnlyRoute)[] =
  undocumentedRoutes<SupplementalRoute | SpecOnlyRoute>(GAPS);
`;
}

export function regenerateIndex(): number {
  const bases = gapFileBases(readdirSync(join(ROOT, GAPS_DIR)));
  writeFileSync(join(ROOT, INDEX_PATH), generateIndex(bases));
  return bases.length;
}

export function indexSummary(count: number): string {
  return `wrote ${INDEX_PATH} (${countNoun(count, "gap file", "gap files")})`;
}

if (import.meta.main) {
  console.log(indexSummary(regenerateIndex()));
}
