/**
 * Renders src/sections/webhooks/events.ts from GitHub's webhooks OpenAPI description as @octokit/openapi-webhooks
 * ships it: the events whose supported-webhook-types names "repository", spelled as the wire event name.
 *   bun .github/scripts/gen-webhook-events.ts  -> rewrites the file
 *   bun run build:check                        -> regenerates and fails on drift, so a package bump that adds or drops
 *                                                 a repository event fails until the file is regenerated and committed
 *   test/scripts/gen-webhook-events.test.ts    -> pins the committed file to a fresh render
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..", "..");
export const EVENTS_PATH = "src/sections/webhooks/events.ts";
const DESCRIPTOR = "@octokit/openapi-webhooks/generated/api.github.com.json";

/** The slice of the descriptor the derivation reads; the rest of each webhook entry is its payload schema. */
export interface WebhooksDescriptor {
  readonly webhooks: Readonly<
    Record<
      string,
      {
        readonly post?: {
          readonly externalDocs?: { readonly url?: string };
          readonly "x-github"?: {
            readonly subcategory?: string;
            readonly "supported-webhook-types"?: readonly string[];
          };
        };
      }
    >
  >;
}

export interface WebhookVocabulary {
  /** Sorted wire event names, without the "*" wildcard (the schema adds it). */
  readonly events: readonly string[];
  /** GitHub's reference page, the externalDocs url every entry points at, minus its anchor. */
  readonly reference: string;
}

/** A descriptor entry missing a field the derivation reads is refused, not skipped: a skipped entry would drop an event
 * GitHub still delivers and the parser would start refusing a valid file. */
function required<T>(value: T | undefined, path: string): T {
  if (value === undefined) {
    throw new Error(`${DESCRIPTOR}: webhooks.${path} is missing; the descriptor shape changed`);
  }
  return value;
}

export function repositoryWebhookVocabulary(doc: WebhooksDescriptor): WebhookVocabulary {
  const events = new Set<string>();
  const references = new Set<string>();
  for (const [hook, entry] of Object.entries(doc.webhooks)) {
    const post = required(entry.post, `${hook}.post`);
    const github = required(post["x-github"], `${hook}.post.x-github`);
    const scopes = required(
      github["supported-webhook-types"],
      `${hook}.post.x-github.supported-webhook-types`,
    );
    const slug = required(github.subcategory, `${hook}.post.x-github.subcategory`);
    const url = required(post.externalDocs?.url, `${hook}.post.externalDocs.url`);
    if (!scopes.includes("repository")) {
      continue;
    }
    // The subcategory is the docs slug (custom-property-values, issue-dependencies, sub-issues); the wire name GitHub
    // accepts on a hook and sends in X-GitHub-Event is snake_case, the same rewrite @octokit/webhooks applies.
    events.add(slug.replaceAll("-", "_"));
    references.add(url.split("#")[0] as string);
  }
  if (events.size === 0) {
    throw new Error(
      `${DESCRIPTOR}: no webhook names "repository" among its supported-webhook-types; the scope vocabulary changed`,
    );
  }
  if (references.size !== 1) {
    throw new Error(
      `${DESCRIPTOR}: repository webhooks point at ${references.size} reference pages, expected one: ${[...references].join(", ")}`,
    );
  }
  return { events: [...events].sort(), reference: [...references][0] as string };
}

/** biome's lineWidth is 100: the render matches what `biome check --write` would produce, or build:check would see drift. */
function renderReference(reference: string): string {
  const inline = `export const WEBHOOK_EVENTS_REFERENCE = ${JSON.stringify(reference)};`;
  if (inline.length <= 100) {
    return inline;
  }
  return `export const WEBHOOK_EVENTS_REFERENCE =\n  ${JSON.stringify(reference)};`;
}

export function renderWebhookEvents(vocabulary: WebhookVocabulary): string {
  return `/**
 * GENERATED by gen-webhook-events.ts - do not edit. The events GitHub delivers to repository webhooks, from
 * GitHub's webhooks OpenAPI description as @octokit/openapi-webhooks ships it (generated/api.github.com.json):
 * every webhook whose supported-webhook-types names "repository", spelled as the wire event name. Regenerate
 * with \`bun .github/scripts/gen-webhook-events.ts\` after a package bump.
 */

/** GitHub's reference page for the events, the externalDocs url the descriptor's entries point at. */
${renderReference(vocabulary.reference)}

/** Sorted, without the "*" wildcard, which the schema adds. */
export const REPOSITORY_WEBHOOK_EVENTS = [
${vocabulary.events.map((event) => `  ${JSON.stringify(event)},`).join("\n")}
] as const;
`;
}

/** The one dot-com file of the eight the package ships; its index would parse every GHES descriptor too. */
export async function readDescriptor(): Promise<WebhooksDescriptor> {
  const module = await import("@octokit/openapi-webhooks/generated/api.github.com.json", {
    with: { type: "json" },
  });
  return module.default as WebhooksDescriptor;
}

export async function regenerateWebhookEvents(): Promise<number> {
  const vocabulary = repositoryWebhookVocabulary(await readDescriptor());
  writeFileSync(join(ROOT, EVENTS_PATH), renderWebhookEvents(vocabulary));
  return vocabulary.events.length;
}

if (import.meta.main) {
  console.log(`wrote ${EVENTS_PATH} (${await regenerateWebhookEvents()} events)`);
}
