/**
 * GENERATED by gen-gaps-index.ts - do not edit. Every pending upstream gap,
 * aggregated in sorted file order; regenerate with
 * `bun .github/scripts/gen-gaps-index.ts` after adding, deleting, or
 * transforming a gap file. The derivations below degrade gracefully to an
 * empty gaps set, so this file survives an empty directory.
 */

import { undocumentedRoutes } from "./gap.js";
import { GAP as lfs } from "./lfs.js";

const GAPS = [
  lfs,
] as const;

type GapUnion = (typeof GAPS)[number];

/**
 * Routes GitHub documents but the pinned @octokit/types release does not
 * carry yet: the octokit-kind gaps' routes (spec-only gaps are keyof
 * Endpoints already). Only the route STRING is consumed (never octokit's
 * parameter/response typing), so the literal union defineGap preserves is
 * enough; an empty GAPS degrades it to never.
 */
export type SupplementalRoute = Extract<GapUnion, { kind: "octokit" }>["routes"][number];

/** The spec-only gaps' routes: typed by octokit, absent from the descriptor. */
type SpecOnlyRoute = Extract<GapUnion, { kind: "spec-only" }>["routes"][number];

/**
 * The routes GitHub's api.github.com OpenAPI descriptor does not document:
 * every spec-only gap's, plus those of octokit-kind gaps marked
 * documentedInSpec: false. Consumed by test/e2e/openapi/paths.ts, which
 * excludes their paths from the spec trim and exempts exactly these
 * METHOD+path pairs from the e2e unknown-route check.
 */
export const UNDOCUMENTED_ROUTES: readonly (SupplementalRoute | SpecOnlyRoute)[] =
  undocumentedRoutes<SupplementalRoute | SpecOnlyRoute>(GAPS);
