/**
 * GENERATED by gen-webhook-events.ts - do not edit. The events GitHub delivers to repository webhooks, from
 * GitHub's webhooks OpenAPI description as @octokit/openapi-webhooks ships it (generated/api.github.com.json):
 * every webhook whose supported-webhook-types names "repository", spelled as the wire event name. Regenerate
 * with `bun .github/scripts/gen-webhook-events.ts` after a package bump.
 */

/** GitHub's reference page for the events, the externalDocs url the descriptor's entries point at. */
export const WEBHOOK_EVENTS_REFERENCE =
  "https://docs.github.com/webhooks/webhook-events-and-payloads";

/** Sorted, without the "*" wildcard, which the schema adds. */
export const REPOSITORY_WEBHOOK_EVENTS = [
  "branch_protection_configuration",
  "branch_protection_rule",
  "check_run",
  "check_suite",
  "code_scanning_alert",
  "commit_comment",
  "create",
  "custom_property_values",
  "delete",
  "dependabot_alert",
  "deploy_key",
  "deployment",
  "deployment_status",
  "discussion",
  "discussion_comment",
  "fork",
  "gollum",
  "issue_comment",
  "issue_dependencies",
  "issues",
  "label",
  "member",
  "meta",
  "milestone",
  "package",
  "page_build",
  "ping",
  "project",
  "project_card",
  "project_column",
  "public",
  "pull_request",
  "pull_request_review",
  "pull_request_review_comment",
  "pull_request_review_thread",
  "push",
  "registry_package",
  "release",
  "repository",
  "repository_advisory",
  "repository_import",
  "repository_ruleset",
  "repository_vulnerability_alert",
  "secret_scanning_alert",
  "secret_scanning_alert_location",
  "secret_scanning_scan",
  "security_and_analysis",
  "star",
  "status",
  "sub_issues",
  "team_add",
  "watch",
  "workflow_job",
  "workflow_run",
] as const;
